Repository omise/omise-java, pull requests merged in 2019-05, with the labels that each got.

#73 Added TrueMoney to SourceType.
  src/main/java/co/omise/models/SourceType.java
  src/test/java/co/omise/models/SourceTypeTest.java
Labels: enhancement, v3.0

#71 Support Econtext SourceType
  src/main/java/co/omise/models/Source.java
  src/main/java/co/omise/models/SourceType.java
Labels: enhancement

#74 Add new properties to Dispute model
  src/main/java/co/omise/models/Dispute.java
  src/main/java/co/omise/models/DisputeReasonCode.java
  src/test/java/co/omise/requests/DisputeRequestTest.java
  src/test/resources/testdata/fixtures/api.omise.co/disputes/dspt_test_5089off452g5m5te7xs-get.json
Labels: enhancement, v3.0

#75 Added expires_at param to Charge request
  .idea/modules/omise-java_main.iml
  .idea/modules/omise-java_test.iml
  src/main/java/co/omise/models/Charge.java
  src/main/java/co/omise/models/SourceType.java
  src/test/java/co/omise/ClientTest.java
  src/test/java/co/omise/models/SourceTypeTest.java
Labels: enhancement

#76 Added TrueMoney as a new SourceType
  src/main/java/co/omise/models/SourceType.java
  src/test/java/co/omise/models/SourceTypeTest.java
Labels: enhancement

#77 Release version 2.7.8
  CHANGELOG.md
  README.md
  build.gradle
Labels: release

#78 Default value for Source type
  src/main/java/co/omise/Serializer.java
  src/main/java/co/omise/models/SourceType.java
Labels: enhancement, v3.0

#79 Support JP bank account.
  src/main/java/co/omise/models/BankAccount.java
Labels: enhancement, v3.0
