Repository omise/omise-java, pull requests merged in 2020-02, with the labels that each got.

#96 Upgrade shadowJar
  build.gradle
Labels: bug

#97 T19167 - Add `zero_interest_installments` to Source model
  .circleci/config.yml
  src/main/java/co/omise/models/Source.java
Labels: enhancement

#98 Release version 3.0.2
  CHANGELOG.md
  build.gradle
Labels: release

#99 add `zero_interest_installments` attribute
  src/main/java/co/omise/models/Charge.java
  src/main/java/co/omise/models/Source.java
  src/test/java/co/omise/live/LiveChargeRequestTest.java
  src/test/java/co/omise/live/LiveSourceRequestTest.java
Labels: enhancement
